/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.umn.cs.distributedkeyvaluestore;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-03-30")
public class FileServerMetaData implements org.apache.thrift.TBase<FileServerMetaData, FileServerMetaData._Fields>, java.io.Serializable, Cloneable, Comparable<FileServerMetaData> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("FileServerMetaData");

  private static final org.apache.thrift.protocol.TField FILEINFOS_FIELD_DESC = new org.apache.thrift.protocol.TField("fileinfos", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new FileServerMetaDataStandardSchemeFactory());
    schemes.put(TupleScheme.class, new FileServerMetaDataTupleSchemeFactory());
  }

  public List<FileInfo> fileinfos; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    FILEINFOS((short)1, "fileinfos");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // FILEINFOS
          return FILEINFOS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FILEINFOS, new org.apache.thrift.meta_data.FieldMetaData("fileinfos", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT            , "FileInfo"))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(FileServerMetaData.class, metaDataMap);
  }

  public FileServerMetaData() {
  }

  public FileServerMetaData(
    List<FileInfo> fileinfos)
  {
    this();
    this.fileinfos = fileinfos;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public FileServerMetaData(FileServerMetaData other) {
    if (other.isSetFileinfos()) {
      List<FileInfo> __this__fileinfos = new ArrayList<FileInfo>(other.fileinfos.size());
      for (FileInfo other_element : other.fileinfos) {
        __this__fileinfos.add(other_element);
      }
      this.fileinfos = __this__fileinfos;
    }
  }

  public FileServerMetaData deepCopy() {
    return new FileServerMetaData(this);
  }

  @Override
  public void clear() {
    this.fileinfos = null;
  }

  public int getFileinfosSize() {
    return (this.fileinfos == null) ? 0 : this.fileinfos.size();
  }

  public java.util.Iterator<FileInfo> getFileinfosIterator() {
    return (this.fileinfos == null) ? null : this.fileinfos.iterator();
  }

  public void addToFileinfos(FileInfo elem) {
    if (this.fileinfos == null) {
      this.fileinfos = new ArrayList<FileInfo>();
    }
    this.fileinfos.add(elem);
  }

  public List<FileInfo> getFileinfos() {
    return this.fileinfos;
  }

  public FileServerMetaData setFileinfos(List<FileInfo> fileinfos) {
    this.fileinfos = fileinfos;
    return this;
  }

  public void unsetFileinfos() {
    this.fileinfos = null;
  }

  /** Returns true if field fileinfos is set (has been assigned a value) and false otherwise */
  public boolean isSetFileinfos() {
    return this.fileinfos != null;
  }

  public void setFileinfosIsSet(boolean value) {
    if (!value) {
      this.fileinfos = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case FILEINFOS:
      if (value == null) {
        unsetFileinfos();
      } else {
        setFileinfos((List<FileInfo>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case FILEINFOS:
      return getFileinfos();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case FILEINFOS:
      return isSetFileinfos();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof FileServerMetaData)
      return this.equals((FileServerMetaData)that);
    return false;
  }

  public boolean equals(FileServerMetaData that) {
    if (that == null)
      return false;

    boolean this_present_fileinfos = true && this.isSetFileinfos();
    boolean that_present_fileinfos = true && that.isSetFileinfos();
    if (this_present_fileinfos || that_present_fileinfos) {
      if (!(this_present_fileinfos && that_present_fileinfos))
        return false;
      if (!this.fileinfos.equals(that.fileinfos))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_fileinfos = true && (isSetFileinfos());
    list.add(present_fileinfos);
    if (present_fileinfos)
      list.add(fileinfos);

    return list.hashCode();
  }

  @Override
  public int compareTo(FileServerMetaData other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetFileinfos()).compareTo(other.isSetFileinfos());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFileinfos()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fileinfos, other.fileinfos);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("FileServerMetaData(");
    boolean first = true;

    sb.append("fileinfos:");
    if (this.fileinfos == null) {
      sb.append("null");
    } else {
      sb.append(this.fileinfos);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FileServerMetaDataStandardSchemeFactory implements SchemeFactory {
    public FileServerMetaDataStandardScheme getScheme() {
      return new FileServerMetaDataStandardScheme();
    }
  }

  private static class FileServerMetaDataStandardScheme extends StandardScheme<FileServerMetaData> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, FileServerMetaData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // FILEINFOS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.fileinfos = new ArrayList<FileInfo>(_list0.size);
                FileInfo _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = new FileInfo();
                  _elem1.read(iprot);
                  struct.fileinfos.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setFileinfosIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, FileServerMetaData struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.fileinfos != null) {
        oprot.writeFieldBegin(FILEINFOS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.fileinfos.size()));
          for (FileInfo _iter3 : struct.fileinfos)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FileServerMetaDataTupleSchemeFactory implements SchemeFactory {
    public FileServerMetaDataTupleScheme getScheme() {
      return new FileServerMetaDataTupleScheme();
    }
  }

  private static class FileServerMetaDataTupleScheme extends TupleScheme<FileServerMetaData> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, FileServerMetaData struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetFileinfos()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetFileinfos()) {
        {
          oprot.writeI32(struct.fileinfos.size());
          for (FileInfo _iter4 : struct.fileinfos)
          {
            _iter4.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, FileServerMetaData struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.fileinfos = new ArrayList<FileInfo>(_list5.size);
          FileInfo _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = new FileInfo();
            _elem6.read(iprot);
            struct.fileinfos.add(_elem6);
          }
        }
        struct.setFileinfosIsSet(true);
      }
    }
  }

}

