/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.umn.cs.distributedkeyvaluestore;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-03-30")
public class Response implements org.apache.thrift.TBase<Response, Response._Fields>, java.io.Serializable, Cloneable, Comparable<Response> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Response");

  private static final org.apache.thrift.protocol.TField TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("type", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField READ_RESPONSE_FIELD_DESC = new org.apache.thrift.protocol.TField("readResponse", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField WRITE_RESPONSE_FIELD_DESC = new org.apache.thrift.protocol.TField("writeResponse", org.apache.thrift.protocol.TType.STRUCT, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ResponseTupleSchemeFactory());
  }

  /**
   * 
   * @see Type
   */
  public Type type; // required
  public edu.umn.cs.distributedkeyvaluestore.ReadResponse readResponse; // optional
  public edu.umn.cs.distributedkeyvaluestore.WriteResponse writeResponse; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see Type
     */
    TYPE((short)1, "type"),
    READ_RESPONSE((short)2, "readResponse"),
    WRITE_RESPONSE((short)3, "writeResponse");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TYPE
          return TYPE;
        case 2: // READ_RESPONSE
          return READ_RESPONSE;
        case 3: // WRITE_RESPONSE
          return WRITE_RESPONSE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.READ_RESPONSE,_Fields.WRITE_RESPONSE};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TYPE, new org.apache.thrift.meta_data.FieldMetaData("type", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, Type.class)));
    tmpMap.put(_Fields.READ_RESPONSE, new org.apache.thrift.meta_data.FieldMetaData("readResponse", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, edu.umn.cs.distributedkeyvaluestore.ReadResponse.class)));
    tmpMap.put(_Fields.WRITE_RESPONSE, new org.apache.thrift.meta_data.FieldMetaData("writeResponse", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, edu.umn.cs.distributedkeyvaluestore.WriteResponse.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Response.class, metaDataMap);
  }

  public Response() {
  }

  public Response(
    Type type)
  {
    this();
    this.type = type;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Response(Response other) {
    if (other.isSetType()) {
      this.type = other.type;
    }
    if (other.isSetReadResponse()) {
      this.readResponse = new edu.umn.cs.distributedkeyvaluestore.ReadResponse(other.readResponse);
    }
    if (other.isSetWriteResponse()) {
      this.writeResponse = new edu.umn.cs.distributedkeyvaluestore.WriteResponse(other.writeResponse);
    }
  }

  public Response deepCopy() {
    return new Response(this);
  }

  @Override
  public void clear() {
    this.type = null;
    this.readResponse = null;
    this.writeResponse = null;
  }

  /**
   * 
   * @see Type
   */
  public Type getType() {
    return this.type;
  }

  /**
   * 
   * @see Type
   */
  public Response setType(Type type) {
    this.type = type;
    return this;
  }

  public void unsetType() {
    this.type = null;
  }

  /** Returns true if field type is set (has been assigned a value) and false otherwise */
  public boolean isSetType() {
    return this.type != null;
  }

  public void setTypeIsSet(boolean value) {
    if (!value) {
      this.type = null;
    }
  }

  public edu.umn.cs.distributedkeyvaluestore.ReadResponse getReadResponse() {
    return this.readResponse;
  }

  public Response setReadResponse(edu.umn.cs.distributedkeyvaluestore.ReadResponse readResponse) {
    this.readResponse = readResponse;
    return this;
  }

  public void unsetReadResponse() {
    this.readResponse = null;
  }

  /** Returns true if field readResponse is set (has been assigned a value) and false otherwise */
  public boolean isSetReadResponse() {
    return this.readResponse != null;
  }

  public void setReadResponseIsSet(boolean value) {
    if (!value) {
      this.readResponse = null;
    }
  }

  public edu.umn.cs.distributedkeyvaluestore.WriteResponse getWriteResponse() {
    return this.writeResponse;
  }

  public Response setWriteResponse(edu.umn.cs.distributedkeyvaluestore.WriteResponse writeResponse) {
    this.writeResponse = writeResponse;
    return this;
  }

  public void unsetWriteResponse() {
    this.writeResponse = null;
  }

  /** Returns true if field writeResponse is set (has been assigned a value) and false otherwise */
  public boolean isSetWriteResponse() {
    return this.writeResponse != null;
  }

  public void setWriteResponseIsSet(boolean value) {
    if (!value) {
      this.writeResponse = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TYPE:
      if (value == null) {
        unsetType();
      } else {
        setType((Type)value);
      }
      break;

    case READ_RESPONSE:
      if (value == null) {
        unsetReadResponse();
      } else {
        setReadResponse((edu.umn.cs.distributedkeyvaluestore.ReadResponse)value);
      }
      break;

    case WRITE_RESPONSE:
      if (value == null) {
        unsetWriteResponse();
      } else {
        setWriteResponse((edu.umn.cs.distributedkeyvaluestore.WriteResponse)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TYPE:
      return getType();

    case READ_RESPONSE:
      return getReadResponse();

    case WRITE_RESPONSE:
      return getWriteResponse();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TYPE:
      return isSetType();
    case READ_RESPONSE:
      return isSetReadResponse();
    case WRITE_RESPONSE:
      return isSetWriteResponse();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Response)
      return this.equals((Response)that);
    return false;
  }

  public boolean equals(Response that) {
    if (that == null)
      return false;

    boolean this_present_type = true && this.isSetType();
    boolean that_present_type = true && that.isSetType();
    if (this_present_type || that_present_type) {
      if (!(this_present_type && that_present_type))
        return false;
      if (!this.type.equals(that.type))
        return false;
    }

    boolean this_present_readResponse = true && this.isSetReadResponse();
    boolean that_present_readResponse = true && that.isSetReadResponse();
    if (this_present_readResponse || that_present_readResponse) {
      if (!(this_present_readResponse && that_present_readResponse))
        return false;
      if (!this.readResponse.equals(that.readResponse))
        return false;
    }

    boolean this_present_writeResponse = true && this.isSetWriteResponse();
    boolean that_present_writeResponse = true && that.isSetWriteResponse();
    if (this_present_writeResponse || that_present_writeResponse) {
      if (!(this_present_writeResponse && that_present_writeResponse))
        return false;
      if (!this.writeResponse.equals(that.writeResponse))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_type = true && (isSetType());
    list.add(present_type);
    if (present_type)
      list.add(type.getValue());

    boolean present_readResponse = true && (isSetReadResponse());
    list.add(present_readResponse);
    if (present_readResponse)
      list.add(readResponse);

    boolean present_writeResponse = true && (isSetWriteResponse());
    list.add(present_writeResponse);
    if (present_writeResponse)
      list.add(writeResponse);

    return list.hashCode();
  }

  @Override
  public int compareTo(Response other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetType()).compareTo(other.isSetType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.type, other.type);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetReadResponse()).compareTo(other.isSetReadResponse());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReadResponse()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.readResponse, other.readResponse);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetWriteResponse()).compareTo(other.isSetWriteResponse());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWriteResponse()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.writeResponse, other.writeResponse);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Response(");
    boolean first = true;

    sb.append("type:");
    if (this.type == null) {
      sb.append("null");
    } else {
      sb.append(this.type);
    }
    first = false;
    if (isSetReadResponse()) {
      if (!first) sb.append(", ");
      sb.append("readResponse:");
      if (this.readResponse == null) {
        sb.append("null");
      } else {
        sb.append(this.readResponse);
      }
      first = false;
    }
    if (isSetWriteResponse()) {
      if (!first) sb.append(", ");
      sb.append("writeResponse:");
      if (this.writeResponse == null) {
        sb.append("null");
      } else {
        sb.append(this.writeResponse);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (type == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'type' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (readResponse != null) {
      readResponse.validate();
    }
    if (writeResponse != null) {
      writeResponse.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ResponseStandardSchemeFactory implements SchemeFactory {
    public ResponseStandardScheme getScheme() {
      return new ResponseStandardScheme();
    }
  }

  private static class ResponseStandardScheme extends StandardScheme<Response> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Response struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.type = edu.umn.cs.distributedkeyvaluestore.Type.findByValue(iprot.readI32());
              struct.setTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // READ_RESPONSE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.readResponse = new edu.umn.cs.distributedkeyvaluestore.ReadResponse();
              struct.readResponse.read(iprot);
              struct.setReadResponseIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // WRITE_RESPONSE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.writeResponse = new edu.umn.cs.distributedkeyvaluestore.WriteResponse();
              struct.writeResponse.read(iprot);
              struct.setWriteResponseIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Response struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.type != null) {
        oprot.writeFieldBegin(TYPE_FIELD_DESC);
        oprot.writeI32(struct.type.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.readResponse != null) {
        if (struct.isSetReadResponse()) {
          oprot.writeFieldBegin(READ_RESPONSE_FIELD_DESC);
          struct.readResponse.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.writeResponse != null) {
        if (struct.isSetWriteResponse()) {
          oprot.writeFieldBegin(WRITE_RESPONSE_FIELD_DESC);
          struct.writeResponse.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ResponseTupleSchemeFactory implements SchemeFactory {
    public ResponseTupleScheme getScheme() {
      return new ResponseTupleScheme();
    }
  }

  private static class ResponseTupleScheme extends TupleScheme<Response> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Response struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI32(struct.type.getValue());
      BitSet optionals = new BitSet();
      if (struct.isSetReadResponse()) {
        optionals.set(0);
      }
      if (struct.isSetWriteResponse()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetReadResponse()) {
        struct.readResponse.write(oprot);
      }
      if (struct.isSetWriteResponse()) {
        struct.writeResponse.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Response struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.type = edu.umn.cs.distributedkeyvaluestore.Type.findByValue(iprot.readI32());
      struct.setTypeIsSet(true);
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.readResponse = new edu.umn.cs.distributedkeyvaluestore.ReadResponse();
        struct.readResponse.read(iprot);
        struct.setReadResponseIsSet(true);
      }
      if (incoming.get(1)) {
        struct.writeResponse = new edu.umn.cs.distributedkeyvaluestore.WriteResponse();
        struct.writeResponse.read(iprot);
        struct.setWriteResponseIsSet(true);
      }
    }
  }

}

